pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher'
include ':unityLibrary'
include ':unity_libary:unityLibrary'
project(':unityLibrary').projectDir = file(rootProject.projectDir, '../unityLibrary')

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()

        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}