name: Unity Android CI

on:
  push:
    branches: [main, code, documents]
  pull_request:
    branches: [main, code, documents] 

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Cache Library folder
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-${{ runner.os }}-

    - name: Vale Linter
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-check
        fail_on_error: true
        files: "**/*.md"

    - name: Check for Unity License
      run: |
        if [ -z "$UNITY_LICENSE" ]; then
          echo "UNITY_LICENSE secret is not set. Please add your Unity license file as a secret named UNITY_LICENSE." && exit 1
        else
          echo "UNITY_LICENSE secret found."
        fi
      shell: bash
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    - name: Cache Unity
      uses: actions/cache@v3
      with:
        path: ~/.cache/unity3d 
        key: UnityCache

    - name: Build project for Android
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: 2021.3.16f1 # Use a valid Unity version
        targetPlatform: Android
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: build-android 
        path: build/Android/*.apk 